// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhPcs0RYE7quZDrCFkOI2L5ObUP5QK0M',
    appId: '1:405604947727:web:128dae78fa2f13dfab507a',
    messagingSenderId: '405604947727',
    projectId: 'demed-d90d6',
    authDomain: 'demed-d90d6.firebaseapp.com',
    storageBucket: 'demed-d90d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD41LJCGXBjLKCLwK3vMW4nGpC21fGv9es',
    appId: '1:405604947727:android:60bbe0a79b4d411dab507a',
    messagingSenderId: '405604947727',
    projectId: 'demed-d90d6',
    storageBucket: 'demed-d90d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8FjlM8tvrwBi_qrypDmfQ9MwOiaiRT5g',
    appId: '1:405604947727:ios:fa3bec878434913eab507a',
    messagingSenderId: '405604947727',
    projectId: 'demed-d90d6',
    storageBucket: 'demed-d90d6.appspot.com',
    iosClientId: '405604947727-bs39ugub67gugdlstl4pfpg7emtqd8ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.decentralisedMedicalRecords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8FjlM8tvrwBi_qrypDmfQ9MwOiaiRT5g',
    appId: '1:405604947727:ios:fa3bec878434913eab507a',
    messagingSenderId: '405604947727',
    projectId: 'demed-d90d6',
    storageBucket: 'demed-d90d6.appspot.com',
    iosClientId: '405604947727-bs39ugub67gugdlstl4pfpg7emtqd8ds.apps.googleusercontent.com',
    iosBundleId: 'com.example.decentralisedMedicalRecords',
  );
}
